version: '3.7'

services:
  web_v16:
    image: aosdevs/odoocast:odoo.debian.16.0.1.2.5.agilecar
    ports:
      - "8069:8069"  # Mapeando para uma porta diferente no host
    volumes:
      - odoo-web-data-v16:/var/lib/odoo
    environment:
      - HOST=db_v16
      - USER=odoo
      - PASSWORD=odoo
    command: 
      odoo -c /etc/odoo/odoo.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - odoo_overlay

  db-odoocast:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-v16:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432  # Mapeando para uma porta diferente no host
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - odoo_overlay

volumes:
  odoo-web-data-v16:
  odoo-db-data-v16:

networks:
  odoo_overlay:
    driver: overlay