version: '3'
services:
  db:
    user: root
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-16-db-postgresql:/var/lib/postgresql/data
    networks:
      - odoo-16-net
  pgadmin4:
    user: root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@odoocast.com.br
      PGADMIN_DEFAULT_PASSWORD: odoocast@2023
    ports:
      - "8080:80"
    networks:
      - odoo-16-net
    volumes:
      - odoo-16-db-pgadmin4:/var/lib/pgadmin4/data
    depends_on:
      - db
  odoo:
    user: root
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"

    # only for development usage
    # command: sleep infinity
    # only for development usage

    volumes:
      - odoo-16-filestore:/var/lib/odoo
      - ./odoo:/usr/lib/python3/dist-packages/odoo
      - ./extra-addons:/usr/lib/python3/dist-packages/odoo/extra-addons
      - ./data-dir:/usr/lib/python3/dist-packages/odoo/data-dir
      - ./.vscode:/usr/lib/python3/dist-packages/odoo/.vscode
      - ./odoo4devs.conf:/usr/lib/python3/dist-packages/odoo/odoo4devs.conf
    networks:
      - odoo-16-net

volumes:
  odoo-16-db-postgresql:
  odoo-16-db-pgadmin4:
  odoo-16-filestore:

networks:
  odoo-16-net:
    driver: bridge