name: Docker Build & Push
on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Extract commit prefix
        id: extract_prefix
        run: echo "::set-output name=prefix::${GITHUB_SHA::8}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker Image Odoo 14.0.1.0.5
      #   run: | 
      #     docker-compose -f odoocast/14.0/docker-compose.yml build
      #     docker image ls
      #     docker tag 140-odoo-app:latest aosdevs/odoocast:14.0.1.0.5
      #     docker push aosdevs/odoocast:14.0.1.0.5

      - name: Build Docker Image Odoo 16.0.1.2.0
        run: |
          docker buildx build --platform linux/amd64 -t aosdevs/odoocast:odoo.debian.16.0.1.2.6.aulao odoocast/16.0/
          docker push aosdevs/odoocast:odoo.debian.16.0.1.2.6.aulao
